export enum KpiTypeEnum {
  _ = 'kpi.kpi.all',
  _KPI_BUSINESS_RESULT_REVENUE_SELL_IN = 'kpi.title.KPI_BUSINESS_RESULT_REVENUE_SELL_IN',
  _KPI_BUSINESS_RESULT_QUANTITY_SELL_IN = 'kpi.title.KPI_BUSINESS_RESULT_QUANTITY_SELL_IN',
  _KPI_NETWORK_EXPANSION_L1_L1_NEW_ACTIVATION = 'kpi.title.KPI_NETWORK_EXPANSION_L1_L1_NEW_ACTIVATION',
  _KPI_NETWORK_EXPANSION_L1_L1_REAL_DEVELOPMENT = 'kpi.title.KPI_NETWORK_EXPANSION_L1_L1_REAL_DEVELOPMENT',
  _KPI_NETWORK_EXPANSION_L1_EXISTS_ON_SYSTEM = 'kpi.title.KPI_NETWORK_EXPANSION_L1_EXISTS_ON_SYSTEM',
  _KPI_NETWORK_EXPANSION_L1_OPERATE_FOR_DAYS = 'kpi.title.KPI_NETWORK_EXPANSION_L1_OPERATE_FOR_DAYS',
  _KPI_NETWORK_EXPANSION_L1_PURCHASE_IN_DAYS = 'kpi.title.KPI_NETWORK_EXPANSION_L1_PURCHASE_IN_DAYS',
  _KPI_NETWORK_EXPANSION_L1_SELL_IN_DAYS = 'kpi.title.KPI_NETWORK_EXPANSION_L1_SELL_IN_DAYS',
  _KPI_NETWORK_EXPANSION_L1_AVERAGE_INCOME = 'kpi.title.KPI_NETWORK_EXPANSION_L1_AVERAGE_INCOME',
  // _KPI_NETWORK_EXPANSION_L2_L2_NEW_ACTIVATION = 'kpi.title.KPI_NETWORK_EXPANSION_L2_L2_NEW_ACTIVATION',
  // _KPI_NETWORK_EXPANSION_L2_L2_EXISTS_ON_SYSTEM = 'kpi.title.KPI_NETWORK_EXPANSION_L2_L2_EXISTS_ON_SYSTEM',
  _KPI_INVENTORY_AMOUNT = 'kpi.title.KPI_INVENTORY_AMOUNT',
  _KPI_INVENTORY_QUANTITY = 'kpi.title.KPI_INVENTORY_QUANTITY'
}
