export enum PromotionTypeEnum {
  _ = 'promotion.promotion.all',
  _PROMOTION_LINE_QUANTITY_PERCENT = 'promotion.promotion.line.quantity.percent',
  _PROMOTION_LINE_QUANTITY_AMOUNT = 'promotion.promotion.line.quantity.amount',
  _PROMOTION_LINE_QUANTITY_FREEITEM = 'promotion.promotion.line.quantity.free.item',
  _PROMOTION_LINE_AMOUNT_PERCENT = 'promotion.promotion.line.amount.percent',
  _PROMOTION_LINE_AMOUNT_AMOUNT = 'promotion.promotion.line.amount.amount',
  _PROMOTION_LINE_AMOUNT_FREEITEM = 'promotion.promotion.line.amount.free.item',
  _PROMOTION_GROUP_QUANTITY_PERCENT = 'promotion.promotion.group.quantity.percent',
  _PROMOTION_GROUP_QUANTITY_AMOUNT = 'promotion.promotion.group.quantity.amount',
  _PROMOTION_GROUP_QUANTITY_FREEITEM = 'promotion.promotion.group.quantity.free.item',
  _PROMOTION_GROUP_AMOUNT_PERCENT = 'promotion.promotion.group.amount.percent',
  _PROMOTION_GROUP_AMOUNT_AMOUNT = 'promotion.promotion.group.amount.amount',
  _PROMOTION_GROUP_AMOUNT_FREEITEM = 'promotion.promotion.group.amount.free.item',
  _PROMOTION_BUNDLE_QUANTITY_PERCENT = 'promotion.promotion.bundle.quantity.percent',
  _PROMOTION_BUNDLE_QUANTITY_AMOUNT = 'promotion.promotion.bundle.quantity.amount',
  _PROMOTION_BUNDLE_QUANTITY_FREEITEM = 'promotion.promotion.bundle.quantity.free.item',
  _PROMOTION_BUNDLE_AMOUNT_PERCENT = 'promotion.promotion.bundle.amount.percent',
  _PROMOTION_BUNDLE_AMOUNT_AMOUNT = 'promotion.promotion.bundle.amount.amount',
  _PROMOTION_BUNDLE_AMOUNT_FREEITEM = 'promotion.promotion.bundle.amount.free.item',
  _PROMOTION_ORDER_QUANTITY_PERCENT = 'promotion.promotion.order.quantity.percent',
  _PROMOTION_ORDER_QUANTITY_AMOUNT = 'promotion.promotion.order.quantity.amount',
  _PROMOTION_ORDER_QUANTITY_FREEITEM = 'promotion.promotion.order.quantity.free.item',
  _PROMOTION_ORDER_AMOUNT_PERCENT = 'promotion.promotion.order.amount.percent',
  _PROMOTION_ORDER_AMOUNT_AMOUNT = 'promotion.promotion.order.amount.amount',
  _PROMOTION_ORDER_AMOUNT_FREEITEM = 'promotion.promotion.order.amount.free.item',
}
